### ISSUE TITLE
load_GMPD in example folder doesn't work

### ISSUE THREAD

**Issue by melmasri** [melmasri/HP-prediction#2]
I am trying the load_GMPD.R, this part causes lots of warnings can you check it?

`
# Removing parasites not reported to species
# Sys.setlocale('LC_ALL','C') 
dt <- dt[grep("sp[.]",dt$ParasiteCorrectedName, invert=TRUE),]
dt <- dt[grep("ABOLISHED",dt$ParasiteCorrectedName, invert=TRUE),]
dt <- dt[grep("no binomial name",dt$ParasiteCorrectedName, invert=TRUE),]
dt <- dt[grep("not identified to genus",dt$ParasiteCorrectedName, invert=TRUE),]
dt <- dt[grep("SPLITTED in ICTV",dt$ParasiteCorrectedName, invert=TRUE),]
dt <- dt[grep("Diphyllobothrium sp",dt$ParasiteCorrectedName, invert=TRUE),]
`

**Comment by maxfarrell** [comment]
I'm not sure why I had to do this, but I originally had the Sys.setlocale('LC_ALL','C') commented out. I'm not sure if setting this will affect your downstream code though. Try it now.

**Comment by melmasri** [comment]
Ok works, thanks.
